name: postman-pull-request
on: [push, pull_request]
                       
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v1

    - name: Install newman
      run: npm install -g newman

    - name: Run the API and Postman's tests
      run: | 
        newman run "TestAcademy_postman_collection.json"
